frame_rate: 20.0

# Set video mode.
video_mode: format7_mode0     # Full resolution.
#video_mode: format7_mode2     # Pixel binning.

# Set shutter speed manually.
auto_shutter: false
shutter_speed: 0.0004

# Set exposure manually. 0.0 seems to work good for fairly sunny weather while
# -0.5 may be advantageous for cloudy conditions.
auto_exposure: false
exposure: 0.0

# Set gamma (~contrast) and saturation.
# Change of color coding allows to change gamma and saturation on the camera.
format7_color_coding: rgb8
gamma: 2.0
saturation: 125.0

# Set white balance manually. 760/740 are usually good values for sunny
# conditions while 740/720 gives better results in cloudy conditions. 900/655
# are good for the vicon room.
# Launch mbzirc_histogram_viewer white_balance_tool.launch to tune the values to
# a specific condition.
auto_white_balance: false
white_balance_blue: 900
white_balance_red: 655


auto_gain: false
